services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    environment:
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - SERVICES=apigateway,cloudformation,cloudwatch,dynamodb,iam,kinesis,lambda,s3,sqs,ssm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
